export const ROUTE_NAMES = {
  AUTH: "AUTH",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  DASHBOARD: "DASHBOARD",
  NOT_FOUND: "NOT_FOUND",
};

export const PARENT_ROUTES = {
  // SALES: ROUTE_NAMES.DASHBOARD,
  // MERCHANT: ROUTE_NAMES.ACCOUNTS,
  // MERCHANT_DETAILS: ROUTE_NAMES.MERCHANT,
  // TICKET: ROUTE_NAMES.SALES,
  // DRAW: ROUTE_NAMES.SALES,
};
